# ECDSA — Elliptic Curve Digital Signature Algorithm over secp256k1
#
# A digital signature scheme turns a private scalar e into a proof that
# a particular agent produced a given message, without revealing e. The
# proof can be checked by anyone who knows the corresponding public key
# Q = e·G, a point on the curve.
#
# Security foundation — the Elliptic Curve Discrete Logarithm Problem (ECDLP):
#   Given G and Q = e·G, finding e is believed to be computationally
#   infeasible for well-chosen curve parameters. There is no known sub-
#   exponential algorithm for this problem on generic elliptic curves.
#   The best attack runs in O(√N) time via Pollard's rho algorithm.
#
# Two separate modular arithmetic domains appear throughout this file:
#
#   F_P  (mod P):  the coordinate field — every x, y on the curve lives here.
#   Z_N  (mod N):  the scalar field — private keys, nonces, and signature
#                  components are integers reduced modulo the group order N.
#
# Mixing these two domains is the most common source of ECDSA bugs.

import hashlib
import hmac

from src.field_element import FieldElement
from src.point import Point


# ---------------------------------------------------------------------------
# secp256k1 Curve Parameters
# ---------------------------------------------------------------------------
#
# secp256k1 is defined in SEC 2 (SECG, 2010) and is the curve used by
# Bitcoin, Ethereum, and many other cryptocurrencies.
#
# The curve equation is:
#
#   y^2 = x^3 + 7  over  F_P
#
# meaning A = 0 (no x term) and B = 7. The absence of the linear term
# gives the curve extra symmetry and enables certain computational shortcuts.

# P is a prime of the special form 2^256 − 2^32 − 977.  Its near-power-of-2
# structure allows modular reduction to be implemented with only a handful of
# additions and subtractions instead of a full division — important for
# constrained devices. Numerically:
#   P = 2^256 − 2^32 − 2^9 − 2^8 − 2^7 − 2^6 − 2^4 − 1
P = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEFFFFFC2F

A = 0
B = 7

# N is the prime order of the subgroup generated by G — the smallest positive
# integer such that N·G = O.  Because N is prime, Z_N is a field: every
# nonzero element k has a multiplicative inverse k^{-1} mod N.  This is
# essential for computing s = k^{-1}(z + r·e) in the signing step.
#
# Note N < P: the two primes are distinct; do not confuse them.
N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

# G is the generator (base point): a specific point on the curve whose
# x- and y-coordinates are fixed by the standard.  Every public key is
# a scalar multiple of G.  The choice of G is arbitrary in principle;
# the standard simply picks a point with a large prime order N.
Gx = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798
Gy = 0x483ADA7726A3C4655DA4FBFC0E1108A8FD17B448A68554199C47D08FFB10D4B8


# ---------------------------------------------------------------------------
# S256Field — F_P arithmetic for secp256k1
# ---------------------------------------------------------------------------

class S256Field(FieldElement):
    """An element of F_P, the coordinate field of secp256k1.

    FieldElement validates primality by trial division up to √prime.  For
    P ≈ 2^256 that search would require ≈ 2^128 iterations — computationally
    infeasible.  Since P's primality is certified by the secp256k1 standard,
    we bypass __init__ and assign the field prime directly.

    All arithmetic (add, sub, mul, pow, div) is inherited unchanged from
    FieldElement; only the construction is overridden.
    """

    def __init__(self, number, prime=None):
        # Intentionally do NOT call FieldElement.__init__.
        # P is a known prime; trial-division certification is unnecessary.
        # The optional `prime` argument is accepted (and ignored) so that
        # FieldElement's inherited methods — which call self.__class__(n, self.prime)
        # — continue to work when self is an S256Field instance.
        self.prime = P
        self.number = number % P

    def __repr__(self):
        return f"S256Field(0x{self.number:064x})"


# Module-level curve-coefficient singletons — created once and reused by
# every S256Point, so all points share the same Python objects for a and b.
_a = S256Field(A)
_b = S256Field(B)

# G — the generator point.
# Point.__init__ will verify G.y^2 == G.x^3 + 7 inside F_P, confirming that
# the standard-specified coordinates actually lie on the curve.
G = Point(S256Field(Gx), S256Field(Gy), _a, _b)

# INF — the point at infinity (additive identity of the group).
INF = Point(None, None, _a, _b)


# ---------------------------------------------------------------------------
# Signature
# ---------------------------------------------------------------------------

class Signature:
    """An ECDSA signature over secp256k1, consisting of two integers (r, s).

    r is the x-coordinate (mod N) of the ephemeral point R = k·G.
    s encodes the relationship between the nonce k, the message hash z,
    and the private key e via: s ≡ k^{-1}(z + r·e) (mod N).

    Both r and s must lie in [1, N−1]; values outside this range are invalid.
    """

    def __init__(self, r: int, s: int):
        self.r = r
        self.s = s

    def __repr__(self):
        return f"Signature(r=0x{self.r:064x}, s=0x{self.s:064x})"

    def __eq__(self, other):
        if not isinstance(other, Signature):
            return False
        return self.r == other.r and self.s == other.s


# ---------------------------------------------------------------------------
# RFC 6979 — Deterministic Nonce Generation
# ---------------------------------------------------------------------------

def _hmac_sha256(key: bytes, data: bytes) -> bytes:
    return hmac.new(key, data, hashlib.sha256).digest()


def _rfc6979_k(private_key: int, z: int) -> int:
    """Generate a deterministic nonce k from (private_key, z) per RFC 6979.

    The critical weakness of naive ECDSA is randomness in k.  If the random
    number generator is biased or ever repeats a k value, the private key is
    exposed:

      Sony's PlayStation 3 (2010): the same k was used for every firmware
      signature.  Observers collected two signatures on different messages
      z1 and z2, both with the same r = (k·G).x.  Then:
          s1 − s2 ≡ k^{-1}(z1 − z2)  (mod N)
          k ≡ (z1 − z2)(s1 − s2)^{-1}  (mod N)
      and from k the private key follows: e ≡ r^{-1}(s·k − z) (mod N).

    RFC 6979 eliminates this risk by deriving k via a keyed pseudorandom
    function (HMAC-SHA256) seeded with the private key and message hash.
    The construction guarantees:

      Determinism    — same (private_key, z) always yields the same k.
      Uniqueness     — different messages produce different k values.
      Unpredictability — without private_key, k is computationally
                         indistinguishable from a uniform random value.

    Algorithm (RFC 6979 §2.4):
    Let hlen = 32 (SHA-256 output length in bytes), qlen = 32 (byte length
    of the 256-bit group order N).  Both are equal here, which simplifies
    the bit-length adjustments in the general spec.

      1. V = 0x01^{32}
      2. K = 0x00^{32}
      3. K = HMAC_K(V || 0x00 || int2octets(e) || bits2octets(z))
      4. V = HMAC_K(V)
      5. K = HMAC_K(V || 0x01 || int2octets(e) || bits2octets(z))
      6. V = HMAC_K(V)
      7. Repeat:
            V = HMAC_K(V)
            k = int(V)           [since qlen = hlen, no truncation needed]
            if 1 ≤ k ≤ N−1: return k
            K = HMAC_K(V || 0x00)
            V = HMAC_K(V)

    int2octets(x) encodes x as a big-endian 32-byte string.
    bits2octets(z) reduces z mod N and then encodes the result the same way.
    """
    # int2octets: big-endian 32-byte encoding of the private key
    x_bytes = private_key.to_bytes(32, 'big')

    # bits2octets: reduce z mod N, then encode as 32 bytes.
    # RFC 6979 requires this reduction so that k is independent of any
    # high bits of z that lie outside [0, N-1].
    h1_bytes = (z % N).to_bytes(32, 'big')

    V = b'\x01' * 32  # step 1
    K = b'\x00' * 32  # step 2

    # Steps 3–4: first HMAC round — mix in private key and message hash
    K = _hmac_sha256(K, V + b'\x00' + x_bytes + h1_bytes)
    V = _hmac_sha256(K, V)

    # Steps 5–6: second HMAC round — separated by 0x01 to guarantee that
    # the two rounds produce independent outputs even if the inputs are similar
    K = _hmac_sha256(K, V + b'\x01' + x_bytes + h1_bytes)
    V = _hmac_sha256(K, V)

    # Step 7: generate candidate k values until a valid one is found.
    # Since qlen = hlen = 256 bits, one HMAC output fills T exactly, so
    # bits2int(T) is just int.from_bytes(V, 'big') with no truncation.
    # An invalid k (k = 0 or k ≥ N) occurs with probability < 4.3 × 10^{-39}
    # for secp256k1; the fallback loop almost never executes.
    while True:
        V = _hmac_sha256(K, V)
        k = int.from_bytes(V, 'big')
        if 1 <= k <= N - 1:
            return k
        # Rare fallback: update PRNG state and try again
        K = _hmac_sha256(K, V + b'\x00')
        V = _hmac_sha256(K, V)


# ---------------------------------------------------------------------------
# Signing
# ---------------------------------------------------------------------------

def sign(private_key: int, z: int, k: int = None) -> Signature:
    """Produce an ECDSA signature (r, s) for message hash z.

    Derivation of the signing equation s ≡ k^{-1}(z + r·e) (mod N):

    We want a pair (r, s) that encodes a verifiable relationship between the
    message hash z, the signer's private key e, and a public nonce point
    R = k·G — without revealing e or k.

    Choose a secret nonce k ∈ [1, N−1].  Compute R = k·G and set
    r = R.x mod N.  The x-coordinate r is revealed; the y-coordinate and k
    are kept secret.

    Define s to encode the linear constraint:
        k ≡ s^{-1}·z + s^{-1}·r·e  (mod N)         … (*)
    Rearranging (*): s·k ≡ z + r·e (mod N), so:
        s ≡ k^{-1}(z + r·e)  (mod N).

    The reason for this particular form is that (*) lets the verifier
    reconstruct k·G without knowing k:
        k·G = s^{-1}·z·G + s^{-1}·r·(e·G) = u1·G + u2·Q.
    Since k·G = R and R.x = r, the verifier checks (u1·G + u2·Q).x = r.

    Why k must remain secret:
        If k is disclosed, e follows immediately:
            e ≡ r^{-1}(s·k − z)  (mod N).

    Why k must never be reused:
        Two signatures (r, s1) and (r, s2) on messages z1 and z2 with the
        same k share the same r.  Subtracting the signing equations:
            s1 − s2 ≡ k^{-1}(z1 − z2)  (mod N)
            k ≡ (z1 − z2)(s1 − s2)^{-1}  (mod N).
        Then e is recovered as above.  This exact attack broke Sony's PS3.

    Low-s normalisation:
        If (r, s) is a valid signature, so is (r, N − s): they correspond to
        using k and −k as nonces, which produce the same r (since −R and R
        share the same x-coordinate).  Bitcoin's BIP-62 requires s ≤ N/2 to
        make signatures canonical and prevent third-party malleability.

    Args:
        private_key: Scalar e ∈ [1, N−1].
        z:           Message hash as an integer (e.g. from SHA-256).
        k:           Optional explicit nonce. If None, RFC 6979 is used.
                     Passing k directly is intended for testing only and
                     removes the security guarantees of RFC 6979.

    Returns:
        Signature with r ∈ [1, N−1] and s ∈ [1, N//2].
    """
    if k is None:
        k = _rfc6979_k(private_key, z)

    # R = k·G — the ephemeral public key
    R = k * G

    # r = R.x mod N.  R.x is a FieldElement in F_P; we read its integer value
    # and reduce it into the scalar field Z_N.  (P and N are different primes,
    # so this reduction is necessary even though R.x.number < P.)
    r = R.x.number % N

    # k^{-1} mod N: since N is prime, Fermat's Little Theorem gives
    # k^{-1} ≡ k^{N−2} (mod N), but Python 3.8+ provides pow(k, -1, N).
    k_inv = pow(k, -1, N)
    s = k_inv * (z + r * private_key) % N

    # Low-s normalisation (BIP-62 canonical form)
    if s > N // 2:
        s = N - s

    return Signature(r, s)


# ---------------------------------------------------------------------------
# Verification
# ---------------------------------------------------------------------------

def verify(public_key: Point, z: int, sig: Signature) -> bool:
    """Verify an ECDSA signature against a message hash and public key.

    Derivation of the verification equation:

    The signing equation is s ≡ k^{-1}(z + r·e) (mod N).  Setting w = s^{-1}:
        k ≡ w·z + w·r·e  (mod N)
          ≡ w·z + w·r·e  (mod N).

    Let u1 = w·z mod N and u2 = w·r mod N.  Then:
        k·G = (u1 + u2·e)·G = u1·G + u2·(e·G) = u1·G + u2·Q.

    Since R = k·G was the nonce point during signing and r = R.x mod N, the
    verifier checks that (u1·G + u2·Q).x ≡ r (mod N).

    Soundness guarantee (informal):
    An adversary who wants to forge a signature (r, s) for a message z
    without knowing e must find u1, u2 such that (u1·G + u2·Q).x ≡ r.
    But choosing u1, u2 first fixes a point X = u1·G + u2·Q; then the
    required r and z values are determined.  Constructing a forgery for a
    *given* z therefore requires solving the ECDLP for Q.

    Args:
        public_key: Point Q = e·G on the secp256k1 curve.
        z:          Message hash as an integer.
        sig:        Signature(r, s) to verify.

    Returns:
        True iff the signature is valid.
    """
    r, s = sig.r, sig.s

    # Range check: r and s must lie in [1, N−1].
    # r = 0 would mean R = k·G had x-coordinate 0 mod N (astronomically rare
    # for a real nonce, and not producible by the sign() function above).
    # s = 0 makes k_inv * (z + r*e) = 0, implying z + r*e ≡ 0 (mod N), which
    # a legitimate signature avoids.
    if not (1 <= r <= N - 1):
        return False
    if not (1 <= s <= N - 1):
        return False

    # w = s^{-1} mod N
    s_inv = pow(s, -1, N)

    # u1 = w·z mod N,  u2 = w·r mod N
    u1 = s_inv * z % N
    u2 = s_inv * r % N

    # X = u1·G + u2·Q
    X = u1 * G + u2 * public_key

    # If X is the point at infinity, the verification fails.
    # This happens only when u1·G = −u2·Q, i.e. u1/u2 = −e mod N, which
    # for a legitimate signature is effectively impossible.
    if X.x is None:
        return False

    # The signature is valid iff X.x ≡ r (mod N).
    # X.x is a FieldElement in F_P; we reduce it into Z_N before comparing.
    return X.x.number % N == r
